const $=id=>document.getElementById(id),state={items:[],selected:null,revision:''};
const formatDuration=value=>Number.isFinite(value)?`${Math.floor(value/60000)}:${String(Math.floor(value/1000)%60).padStart(2,'0')}`:'Unknown';
const label={mp3:'MP3',original_mp4:'Original MP4',karaoke_mp4:'Karaoke MP4'};
const text=value=>String(value??'');
function filtered(){const query=$('search').value.trim().toLocaleLowerCase();return query?state.items.filter(item=>[item.title,item.artist,item.album,item.relativePath,...(item.aliases||[])].some(value=>text(value).toLocaleLowerCase().includes(query))):state.items}
function renderList(){const shown=filtered(),host=$('items');host.replaceChildren();$('counts').textContent=`${shown.length} shown · ${state.items.length} total`;
 for(const item of shown){const row=document.createElement('div');row.className='item'+(item.id===state.selected?.id?' active':'');const copy=document.createElement('div'),title=document.createElement('strong'),meta=document.createElement('small'),button=document.createElement('button');title.textContent=item.title;meta.textContent=[item.artist,item.album,label[item.kind]].filter(Boolean).join(' · ');copy.append(title,meta);button.type='button';button.textContent='Edit';button.onclick=()=>select(item.id);row.append(copy,button);host.append(row)}}
function select(id){state.selected=state.items.find(item=>item.id===id);const item=state.selected;if(!item)return;$('empty').hidden=true;$('editor').hidden=false;$('heading').textContent=item.title;$('badge').textContent=label[item.kind]||item.kind;
 for(const field of ['title','artist','album'])$(field).value=text(item[field]);$('kind').value=item.kind;$('track').value=item.track??'';$('year').value=item.year??'';$('aliases').value=(item.aliases||[]).join('\n');
 const extension=text(item.extension||item.relativePath?.split('.').pop()).toLocaleLowerCase();for(const option of $('kind').options)option.disabled=extension==='mp3'?option.value!=='mp3':option.value==='mp3';
 $('path').textContent=item.relativePath;$('duration').textContent=formatDuration(item.durationMs);$('source').textContent=item.metadataSource||item.provenance?.title||'Catalog';$('edited').textContent=item.manuallyEditedAt||'Never';$('message').textContent='';$('message').className='';renderList()}
async function load(){const response=await fetch('/api/catalog');if(!response.ok)throw new Error('Unable to load the catalog.');const data=await response.json();state.items=data.items;state.revision=response.headers.get('ETag')||'';$('catalogState').textContent=`${data.filename} · ${data.items.length} files`;renderList();if(state.selected)select(state.selected.id)}
$('search').addEventListener('input',renderList);
$('editor').addEventListener('submit',async event=>{event.preventDefault();if(!state.selected)return;const button=$('save'),message=$('message');button.disabled=true;message.className='';message.textContent='Saving…';
 const nullable=id=>$(id).value===''?null:Number($(id).value),body={title:$('title').value,artist:$('artist').value,album:$('album').value,kind:$('kind').value,track:nullable('track'),year:nullable('year'),aliases:$('aliases').value.split(/\r?\n/)};
 try{const response=await fetch('/api/items/'+encodeURIComponent(state.selected.id),{method:'PATCH',headers:{'Content-Type':'application/json','If-Match':state.revision},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Save failed.');state.revision=response.headers.get('ETag')||state.revision;const index=state.items.findIndex(item=>item.id===data.item.id);state.items[index]=data.item;state.selected=data.item;select(data.item.id);message.textContent='Metadata saved to catalog.json.'}
 catch(error){message.textContent=error.message;message.className='error'}finally{button.disabled=false}});
load().catch(error=>{$('catalogState').textContent=error.message});
